# Generated by Django 3.2.13 on 2022-05-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=30, verbose_name='نوع خودرو')),
                ('car_model', models.CharField(max_length=40, verbose_name='مدل')),
                ('generation_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال ساخت')),
                ('reg_kilometer_indicator', models.BigIntegerField(blank=True, null=True, verbose_name='کیلومتر طی شده')),
                ('paint_color', models.PositiveSmallIntegerField(choices=[(1, 'سفید'), (2, 'مشکی'), (3, 'خاکستری\\(طوسی\\)'), (4, 'قرمز'), (5, 'نارنجی\\(مسی | آجری\\)'), (6, 'آبی'), (7, 'سرمه ای\\(آبی تیره | آبی نفتی\\)'), (8, 'سبز'), (9, 'فسفری'), (10, 'طلایی'), (11, 'نقره ای'), (12, 'یشمی\\(سبز تیره)'), (13, 'بژ\\(کرم | خاکی | شیری\\)'), (14, 'زرد'), (15, 'متفرقه')], verbose_name='رنگ')),
            ],
        ),
    ]
