# Generated by Django 3.2.13 on 2022-05-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careg', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'خودرو', 'verbose_name_plural': 'خودروها'},
        ),
        migrations.AlterField(
            model_name='car',
            name='paint_color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'سفید'), (2, 'مشکی'), (3, 'خاکستری (طوسی)'), (4, 'قرمز'), (5, 'نارنجی (مسی | آجری)'), (6, 'آبی'), (7, 'سرمه ای (آبی تیره | آبی نفتی)'), (8, 'سبز'), (9, 'فسفری'), (10, 'طلایی'), (11, 'نقره ای'), (12, 'یشمی (سبز تیره)'), (13, 'بژ (کرم | خاکی | شیری)'), (14, 'زرد'), (15, 'متفرقه')], verbose_name='رنگ'),
        ),
    ]
